import fs from "fs";
import path from "path";
import axios from "axios";
import {
  SlashCommandBuilder,
  EmbedBuilder
} from "discord.js";

export const data = new SlashCommandBuilder()
  .setName("locker")
  .setDescription("View your Fortnite locker.");

export async function execute(interaction) {
  await interaction.deferReply({ ephemeral: false });

  const userFile = path.join(process.cwd(), "data", "users", `${interaction.user.id}.json`);

  if (!fs.existsSync(userFile)) {
    return interaction.editReply("❌ You are not logged in. Use `/login` first.");
  }

  const auth = JSON.parse(fs.readFileSync(userFile));

  // Contact backend
  let locker;
  try {
    const res = await axios.post(`${process.env.SERVER_URL}/locker/fetch`, {
      deviceAuth: auth.deviceAuth
    });

    locker = res.data;
  } catch (err) {
    console.error(err);
    return interaction.editReply("❌ Failed to fetch locker.");
  }

  // Build embed
  const embed = new EmbedBuilder()
    .setTitle(`${interaction.user.username}'s Locker`)
    .setColor("#00A6FF")
    .addFields(
      {
        name: "Skins",
        value: locker.skins.length ? locker.skins.map(s => s.name).join(", ") : "None",
        inline: false
      },
      {
        name: "Backblings",
        value: locker.backblings.length ? locker.backblings.map(s => s.name).join(", ") : "None",
        inline: false
      },
      {
        name: "Pickaxes",
        value: locker.pickaxes.length ? locker.pickaxes.map(s => s.name).join(", ") : "None",
        inline: false
      },
      {
        name: "Emotes",
        value: locker.emotes.length ? locker.emotes.map(s => s.name).join(", ") : "None",
        inline: false
      },
      {
        name: "Gliders",
        value: locker.gliders.length ? locker.gliders.map(s => s.name).join(", ") : "None",
        inline: false
      }
    )
    .setFooter({ text: "Generated by your Fortnite locker checker" });

  await interaction.editReply({ embeds: [embed] });
}
